import type { GrillState } from '@/types/state'

export function makeState(overrides: Partial<GrillState> = {}): GrillState {
  return {
    ts: 1_700_000_000_000,
    name: 'Backyard',
    units: 'F',
    mode: 'Stop',
    next_mode: 'Stop',
    status: 'inactive',
    display_mode: 'Stop',
    critical_error: false,
    temps: { primary: { Grill: 72 }, food: { Probe1: 70, Probe2: 71 }, aux: {} },
    setpoint: 0,
    notify_targets: { Grill: 0, Probe1: 0, Probe2: 0 },
    smoke_plus: false,
    pwm_control: false,
    duty_cycle: 100,
    p_mode: 2,
    outputs: { auger: false, fan: false, igniter: false, power: false },
    timer: { start: 0, paused: 0, end: 0, shutdown: false },
    lid_open: { detected: false, end_time: 0 },
    startup: { timestamp: 0, start_time: 0, duration: 240 },
    shutdown_duration: 240,
    prime: { duration: 0, amount: 0 },
    recipe: { active: false, paused: false },
    hopper: { level: 80, enabled: true, pellets: 'Traeger Hickory', est_usage_g: 0 },
    notify: [
      { label: 'Grill', name: 'Grill', type: 'probe', req: false, target: 0 },
      { label: 'Grill', name: 'Grill', type: 'probe_limit_high', req: false, target: 0 },
      { label: 'Grill', name: 'Grill', type: 'probe_limit_low', req: false, target: 0 },
      { label: 'Probe1', name: 'Probe-1', type: 'probe', req: false, target: 0 },
      { label: 'Probe1', name: 'Probe-1', type: 'probe_limit_high', req: false, target: 0 },
      { label: 'Probe1', name: 'Probe-1', type: 'probe_limit_low', req: false, target: 0 },
      { label: 'Probe2', name: 'Probe-2', type: 'probe', req: false, target: 0 },
      { label: 'Timer', type: 'timer', req: false },
      { label: 'Hopper', type: 'hopper', req: false },
    ],
    probes: [
      { label: 'Grill', name: 'Grill', type: 'Primary', device: 'sim', port: 'SIM0', enabled: true },
      { label: 'Probe1', name: 'Probe-1', type: 'Food', device: 'sim', port: 'SIM1', enabled: true },
      { label: 'Probe2', name: 'Probe-2', type: 'Food', device: 'sim', port: 'SIM2', enabled: true },
    ],
    probe_status: { P: {}, F: {}, AUX: {} },
    manual: { change: null, output: null, pwm: 100 },
    errors: [],
    warnings: [],
    ...overrides,
  }
}
